parameters:

    # Ignore lists
    obfuscator.scramble_variable.ignore: []
    obfuscator.scramble_private_method.ignore: []
    obfuscator.scramble_private_property.ignore: []
    obfuscator.scramble_use.ignore: []
    obfuscator.scramble_comments.preserve_annotations: true
    obfuscator.scramble_comments.annotations_flavor: "generic"

    # Output printer
    obfuscator.printer: PhpParser\PrettyPrinter\Standard

    # Files to parse
    obfuscator.files: "/\.php$/"

    # PHP version (1 = Prefer PHP7, 2 = Prefer PHP5, 3 = PHP7, 4 = PHP5)
    obfuscator.language: 1

services:

    # Obfuscator
    obfuscator:
        class: Naneau\Obfuscator\Obfuscator
        calls:
            - [setParser, [@obfuscator.parser]]
            - [setTraverser, [@obfuscator.node_traverser]]
            - [setPrettyPrinter, [@obfuscator.pretty_printer]]
            - [setEventDispatcher, [@obfuscator.event_dispatcher]]
            - [setFileRegex, [%obfuscator.files%]]

    # String scrambler
    obfuscator.scrambler:
        class: Naneau\Obfuscator\StringScrambler

    # Node traverser
    obfuscator.node_traverser:
        class: PhpParser\NodeTraverser
        calls:
            - [addVisitor, [@obfuscator.node_visitor.meta]]
            - [addVisitor, [@obfuscator.node_visitor.scramble_variable]]
            - [addVisitor, [@obfuscator.node_visitor.scramble_private_method]]
            - [addVisitor, [@obfuscator.node_visitor.scramble_private_property]]
            - [addVisitor, [@obfuscator.node_visitor.scramble_comment]]

    # Meta
    obfuscator.node_visitor.meta:
        class: Naneau\Obfuscator\Node\Visitor\Meta

    # Variable scrambler
    obfuscator.node_visitor.scramble_variable:
        class: Naneau\Obfuscator\Node\Visitor\ScrambleVariable
        arguments:
            - @obfuscator.scrambler
        calls:
            - [addIgnore, [%obfuscator.scramble_variable.ignore%]]

    # Scramble private methods
    obfuscator.node_visitor.scramble_private_method:
        class: Naneau\Obfuscator\Node\Visitor\ScramblePrivateMethod
        arguments:
            - @obfuscator.scrambler
        calls:
            - [addIgnore, [%obfuscator.scramble_private_method.ignore%]]

    # Scramble private properties
    obfuscator.node_visitor.scramble_private_property:
        class: Naneau\Obfuscator\Node\Visitor\ScramblePrivateProperty
        arguments:
            - @obfuscator.scrambler
        calls:
            - [addIgnore, [%obfuscator.scramble_private_property.ignore%]]

    # Scramble use statements
    obfuscator.node_visitor.scramble_use:
        class: Naneau\Obfuscator\Node\Visitor\ScrambleUse
        arguments:
            - @obfuscator.scrambler
        calls:
            - [addIgnore, [%obfuscator.scramble_use.ignore%]]

    # Scramble comments
    obfuscator.node_visitor.scramble_comment:
        class: Naneau\Obfuscator\Node\Visitor\ScrambleComment
        arguments:
            - @obfuscator.scrambler
        calls:
            - [setPreserveAnnotations, [%obfuscator.scramble_comments.preserve_annotations%]]
            - [setAnnotationsFlavor, [%obfuscator.scramble_comments.annotations_flavor%]]

    # Parser factory
    obfuscator.parser_factory:
        class: PhpParser\ParserFactory

    # Parser
    obfuscator.parser:
        class: PhpParser\Parser
        factory: [@obfuscator.parser_factory, create]
        arguments:
            - %obfuscator.language%

    # Pretty printer
    obfuscator.pretty_printer:
        class: %obfuscator.printer%

    # Event dispatcher
    obfuscator.event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments:
            - @service_container
